// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iajnbguedvmpagcssrll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlham5iZ3VlZHZtcGFnY3NzcmxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NDY3NTIsImV4cCI6MjA4ODMyMjc1Mn0.-U54Xoa1xg0shZV1pb_0U8fDHAa-Ki0Yj2ALCDYnBRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});